CREATE TABLE Idioma(
    idioma_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lengua varchar(15) NOT NULL UNIQUE,
    
    PRIMARY KEY (idioma_id)
);

CREATE TABLE Autor(
    autor_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_y_apellido varchar(50) NOT NULL,
    nombre_de_fantasia varchar(30) NOT NULL,
    fecha_de_nacimiento DATE,
    biografia varchar(1000),
    
    PRIMARY KEY (autor_id)
);


CREATE TABLE Editorial(
    editorial_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    direccion VARCHAR(60) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    
    PRIMARY KEY(editorial_id)
);

CREATE TABLE Libro(
    libro_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo varchar(100) NOT NULL,
    editorial_id int NOT NULL,
    idioma_id int NOT NULL,
    
    PRIMARY KEY(libro_id),
    
    CONSTRAINT fk_editorial_id 
        FOREIGN KEY (editorial_id)
        REFERENCES Editorial(editorial_id),
    CONSTRAINT fk_idioma_id
        FOREIGN KEY (idioma_id)
        REFERENCES Idioma(idioma_id)
);

CREATE TABLE escribe (
    autor_id int NOT NULL,
    libro_id int NOT NULL,
    
    PRIMARY KEY (autor_id,libro_id),
    
    CONSTRAINT fk_autor_id
        FOREIGN KEY (autor_id)
        REFERENCES Autor(autor_id),
    CONSTRAINT fk_libro_id
        FOREIGN KEY (libro_id)
        REFERENCES Libro(libro_id)
);

CREATE TABLE Sector(
    sector_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descripcion varchar(200),
    
    PRIMARY KEY (sector_id)
);

CREATE TABLE Estanteria(
    numero_estanteria INT NOT NULL, 
    sector_id int NOT NULL,
    
    PRIMARY KEY (numero_estanteria, sector_id),
    
    CONSTRAINT fk_sector_id
        FOREIGN KEY (sector_id)
        REFERENCES Sector(sector_id)
);

CREATE TABLE Edicion(
    edicion_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libro_id int NOT NULL,
    isbn varchar(17) NOT NULL UNIQUE,
    indice varchar(1000),
    fecha_de_publicacion DATE NOT NULL,
    
    PRIMARY KEY (edicion_id),
    
    CONSTRAINT fk_libro_id
        FOREIGN KEY (libro_id)
        REFERENCES Libro(libro_id)
);

CREATE TABLE contiene(
    numero_estanteria int NOT NULL,
    sector_id int NOT NULL,
    edicion_id int NOT NULL,
    
    PRIMARY KEY (numero_estanteria,sector_id,edicion_id),
    
    CONSTRAINT fk_nro_est_sector_id
        FOREIGN KEY (numero_estanteria,sector_id)
        REFERENCES Estanteria(numero_estanteria,sector_id),

    CONSTRAINT fk_edicion_id
        FOREIGN KEY (edicion_id)
        REFERENCES Edicion(edicion_id)
        
);


CREATE TABLE Tema(
    tema_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descripcion_tema varchar(100) NOT NULL,
    
    PRIMARY KEY (tema_id)
);

CREATE TABLE esta_relacionado_a(
    edicion_id int NOT NULL,
    tema_id int NOT NULL,

    PRIMARY key(edicion_id, tema_id),
    
    CONSTRAINT fk_edicion_id
        FOREIGN KEY (edicion_id)
        REFERENCES Edicion(edicion_id),

    CONSTRAINT fk_tema_id
        FOREIGN KEY (tema_id)
        REFERENCES Tema(tema_id)
);

CREATE TABLE Palabra_Clave(
    palabra_clave_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    palabra VARCHAR(30) NOT NULL UNIQUE,

    PRIMARY KEY(palabra_clave_id)
);
 
CREATE TABLE tiene_palabras_que_son(
    edicion_id int NOT NULL,
    palabra_clave_id int NOT NULL,

	PRIMARY KEY(edicion_id, palabra_clave_id),

	CONSTRAINT fk_edicion_id
        FOREIGN KEY (edicion_id)
        REFERENCES Edicion(edicion_id),

	CONSTRAINT fk_palabra_clave_id
        FOREIGN KEY (palabra_clave_id)
        REFERENCES Palabra_Clave(palabra_clave_id)
);

CREATE TABLE Ejemplar(
    numero_ejemplar int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    edicion_id int NOT NULL,
	estado_del_ejemplar VARCHAR(128),

	PRIMARY KEY(numero_ejemplar, edicion_id),

	CONSTRAINT fk_edicion_id
        FOREIGN KEY (edicion_id)
        REFERENCES Edicion(edicion_id)
);

CREATE TABLE Lector(
    lector_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_y_apellido VARCHAR(50) NOT NULL,
    telefono VARCHAR (20) NOT NULL,
    cuil VARCHAR (13) NOT NULL UNIQUE,
    
    PRIMARY KEY (lector_id)
);

CREATE TABLE fue_consultado_por(
    fecha_consulta DATE NOT NULL,
    hora_consulta TIME NOT NULL,
	hora_devolucion TIME,
	lector_id int NOT NULL,
	numero_ejemplar int NOT NULL,
	edicion_id int NOT NULL,

	PRIMARY KEY(fecha_consulta, hora_consulta, lector_id, numero_ejemplar, edicion_id),

	CONSTRAINT fk_numero_ejemplar
        FOREIGN KEY (numero_ejemplar, edicion_id)
        REFERENCES Ejemplar(numero_ejemplar, edicion_id),

	CONSTRAINT fk_lector_id
        FOREIGN KEY (lector_id)
        REFERENCES Lector(lector_id)
);

CREATE TABLE Alumno(
    lector_id INT NOT NULL,
    libreta_universitaria VARCHAR(100) NOT NULL,
    
    PRIMARY KEY (lector_id),
    CONSTRAINT fk_lector_id
       FOREIGN KEY (lector_id)
       REFERENCES Lector(lector_id)
);

CREATE TABLE Alumno_Egresado(
    lector_id INT NOT NULL,
    fecha_de_egreso DATE NOT NULL,

    PRIMARY KEY (lector_id),

    CONSTRAINT fk_lector_id
       FOREIGN KEY (lector_id)
       REFERENCES Alumno(lector_id)
);

CREATE TABLE Docente(
    lector_id INT NOT NULL,
    
    PRIMARY KEY (lector_id),

    CONSTRAINT fk_lector_id
       FOREIGN KEY (lector_id)
       REFERENCES Lector(lector_id)
);

CREATE TABLE Materia(
    materia_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR(60) NOT NULL,
    
    PRIMARY KEY (materia_id)
);
 
CREATE TABLE es_dictada_por(
    materia_id INT NOT NULL,
    lector_id_docente INT NOT NULL,
    
    PRIMARY KEY (materia_id, lector_id_docente),
    
    CONSTRAINT fk_materia_id
        FOREIGN KEY (materia_id)
        REFERENCES Materia(materia_id),

    CONSTRAINT fk_lector_id_docente
        FOREIGN KEY (lector_id_docente)
        REFERENCES Docente(lector_id)
);

CREATE TABLE es_bibliografia_recomendada_por(
    edicion_id INT NOT NULL,
    materia_id INT NOT NULL,
    lector_id_docente INT NOT NULL,
    
    PRIMARY KEY (edicion_id, materia_id, lector_id_docente),
    
    CONSTRAINT fk_edicion_id
        FOREIGN KEY (edicion_id)
        REFERENCES Edicion(edicion_id),
        
    CONSTRAINT fk_materia_id_lector_id_docente
        FOREIGN KEY (materia_id, lector_id_docente)
        REFERENCES es_dictada_por(materia_id, lector_id_docente)
);

CREATE TABLE es_bibliografia_de(
    edicion_id INT NOT NULL,
    materia_id INT NOT NULL,
    tipo CHAR(2) NOT NULL,

    CHECK(TIPO = 'OB' OR tipo = 'OP'),
    
    PRIMARY KEY (edicion_id, materia_id),
    
    CONSTRAINT fk_edicion_id
        FOREIGN KEY (edicion_id)
        REFERENCES Edicion(edicion_id),
    CONSTRAINT fk_materia_id
        FOREIGN KEY (materia_id)
        REFERENCES Materia(materia_id)
);

CREATE TABLE Prestamo(
    prestamo_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_entrega DATE NOT NULL,
    fecha_devolucion DATE,
    fecha_limite DATE NOT NULL,
    estado_del_ejemplar VARCHAR(128) NOT NULL,
    edicion_id INT NOT NULL,
    numero_ejemplar INT NOT NULL,
    lector_id INT NOT NULL,
    
    PRIMARY KEY (prestamo_id),
    
    CONSTRAINT fk_edicion_id_numero_ejemplar
        FOREIGN KEY (edicion_id, numero_ejemplar)
        REFERENCES Ejemplar(edicion_id, numero_ejemplar),
    
    CONSTRAINT fk_lector_id
        FOREIGN KEY (lector_id)
        REFERENCES Lector(lector_id)
);
